name: 'lord_stanley'
version: '1.0.0'
profile: 'lord_stanley'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

seeds:
  lord_stanley:
    drafts:
      +column_types:
        season: string

models:
  lord_stanley:
    staging:
      +materialized: table
      +schema: staging
    intermediate:
      +materialized: table
      +schema: intermediate
    mart:
      +materialized: table
      +schema: mart